### ISSUE TITLE
WATCHPUG - Incomplete support for MATIC token

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-telcoin-judging#81]
WATCHPUG

medium

# Incomplete support for MATIC token

## Summary

While the current implementation deliberately handle the case of MATIC token, the support is still incomplete.

## Vulnerability Detail

When the fee token is `MATIC` (`0x0000000000000000000000000000000000001010`), the secondary swap from fee token to TEL token will most certainly fail.

As it won't be able to pull funds from the `safe`, plus, 1inch `_aggregator` also can not pull funds from the feeBuyBack contract.

## Impact

Whenever `MATIC` is used as the fee token, the transaction will fail.

## Code Snippet

https://github.com/sherlock-audit/2022-11-telcoin/blob/main/contracts/fee-buyback/FeeBuyback.sol#L70-L73

https://github.com/sherlock-audit/2022-11-telcoin/blob/main/contracts/fee-buyback/FeeBuyback.sol#L77

## Tool used

Manual Review

## Recommendation

Skip the secondary swap when the fee token is MATIC:

```diff
    //MATIC does not allow for approvals
    //ERC20s only
-    if (token != MATIC) {
+    if (token == MATIC) return false;
      IERC20(token).transferFrom(_safe, address(this), amount);
      IERC20(token).approve(_aggregator, amount);
-    }
```

**Comment by jack-the-pug** [comment]
@amshirif Thanks for the explanation! I think i get it now. While it's quite unconventional to use this MRC20 Matic token to transfer native tokens, but I think you are right, if that's how you are doing it, then this is not a bug.
