### ISSUE TITLE
WATCHPUG - `claimFromIndividualPlugin()` may endup claiming the reward from a different plugin with wrong `auxData` when the index as changed due to `removePlugin()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-telcoin-judging#86]
WATCHPUG

medium

# `claimFromIndividualPlugin()` may endup claiming the reward from a different plugin with wrong `auxData` when the index as changed due to `removePlugin()`

## Summary

When `removePlugin()` happens between the user sends the `claimFromIndividualPlugin()` transaction and before it gets minted, it may lead to lesser rewards as the `auxData` prepared for another plugin will now be used.

## Vulnerability Detail

When a user calls `claimFromIndividualPlugin()`, a `pluginIndex` is used to refer to a plugin.

However, if the `PLUGIN_EDITOR` removed a plugin before the transaction gets minted, the plugin referred by the `pluginIndex` can be changed to another plugin.

As a result, the `auxData` supposed to be supplied to the original plugin is now supplied to another plugin.

## Impact

The user may end up with lesser rewards as a wrong `auxData` is supplied to the wrong plugin.

## Code Snippet

https://github.com/sherlock-audit/2022-11-telcoin/blob/main/contracts/StakingModule.sol#L420-L429

https://github.com/sherlock-audit/2022-11-telcoin/blob/main/contracts/StakingModule.sol#L178-L185

## Tool used

Manual Review

## Recommendation

Consider using `pluginAddress` instead.

**Comment by dmitriia** [comment]
Escalate for 20 USDC
This is temporal fund freeze impact: wrong `auxData` will not cause extra funds claimed, a user will either have the call reverted or receive less funds, still being able to reclaim what is due with the correct `auxData` and `pluginIndex` immediately afterwards.
This way it should be open/closed (recognized as Med or not) simultaneously with #73, #74, that have similar temporary funds freezing outcome.

**Comment by sherlock-admin** [comment]
> Escalate for 20 USDC
> This is temporal fund freeze impact: wrong `auxData` will not cause extra funds claimed, a user will either have the call reverted or receive less funds, still being able to reclaim what is due with the correct `auxData` and `pluginIndex` immediately afterwards.
> This way it should be open/closed (recognized as Med or not) simultaneously with #73, #74, that have similar temporary funds freezing outcome.

You've created a valid escalation for 20 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Escalate for 1 USDC.

If https://github.com/sherlock-audit/2022-11-telcoin-judging/issues/73 count, all duplicate of 73 should count as well.

Thanks!

**Comment by ctf-sec** [comment]
Escalate for 1 USDC.

If https://github.com/sherlock-audit/2022-11-telcoin-judging/issues/73 counts, all duplicate of 73 should count.

Thanks.

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC.
> 
> If https://github.com/sherlock-audit/2022-11-telcoin-judging/issues/73 counts, all duplicate of 73 should count.
> 
> Thanks.
> 

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

> However, if the PLUGIN_EDITOR removed a plugin before the transaction gets minted, the plugin referred by the pluginIndex can be changed to another plugin.

An edge case that results in a temporal freeze of funds.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> > However, if the PLUGIN_EDITOR removed a plugin before the transaction gets minted, the plugin referred by the pluginIndex can be changed to another plugin.
> 
> An edge case that results in a temporal freeze of funds. 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
